require: rubocop-rspec

AllCops:
  Include:
  - "**/*.gemspec"
  - "**/*.podspec"
  - "**/*.jbuilder"
  - "**/*.rake"
  - "**/*.opal"
  - "**/Gemfile"
  - "**/Rakefile"
  - "**/Capfile"
  - "**/Guardfile"
  - "**/Podfile"
  - "**/Thorfile"
  - "**/Vagrantfile"
  - "**/Berksfile"
  - "**/Cheffile"
  - "**/Vagabondfile"
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - vendor/*
  DisplayCopNames: false
  StyleGuideCopsOnly: false

# Rails

Rails/ActionFilter:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

# RSpec

RSpec/DescribeClass:
  Exclude:
    - spec/features/*
    - spec/requests/*
    - spec/lib/tasks/*

Style/StringLiterals:
  SupportedStyles:
    - single_quotes
    - double_quotes

Metrics/LineLength:
  Description: Limit lines to 100 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https
  Exclude:
  - db/seeds.rb

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Documentation:
  Enabled: false
