default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: memorable_development

test:
  <<: *default
  database: memorable_test

production:
  <<: *default
  database: memorable_production
  username: memorable
  password: <%= ENV['MEMORABLE_DATABASE_PASSWORD'] %>
